//! Hand-written Rust types mirroring the protobuf definitions.
//!
//! In production, these are generated by `tonic-build` from `conduit.proto`.
//! We define them manually here so the crate compiles without a build step
//! and can be swapped for generated code when the proto toolchain is set up.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ─── Registration ─────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterRequest {
    pub worker_id: String,
    pub hostname: String,
    pub capacity: u32,
    pub pool_affinity: Vec<String>,
    pub labels: HashMap<String, String>,
    pub version: String,
    pub health_port: u32,
}

// ─── Task Assignment ──────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskAssignment {
    pub assignment_id: String,
    pub dag_id: String,
    pub run_id: String,
    pub task_id: String,
    pub attempt: u32,
    pub spec: TaskSpec,
    pub context: TaskContext,
    pub deadline_epoch_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskSpec {
    pub task_type: TaskType,
    pub script: String,
    pub connection: String,
    pub query: String,
    pub command: String,
    pub args: Vec<String>,
    pub timeout_secs: u64,
    pub resources: ResourceLimits,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum TaskType {
    Unspecified = 0,
    Python = 1,
    Bash = 2,
    Sql = 3,
    Sensor = 4,
    Executable = 5,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceLimits {
    pub cpu_millicores: u32,
    pub memory_mb: u32,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            cpu_millicores: 0,
            memory_mb: 0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskContext {
    pub dag_id: String,
    pub run_id: String,
    pub task_id: String,
    pub attempt: u32,
    pub logical_date_epoch_ms: i64,
    pub environment: String,
    pub params: HashMap<String, String>,
}

// ─── Task Results ─────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskResult {
    pub assignment_id: String,
    pub worker_id: String,
    pub dag_id: String,
    pub run_id: String,
    pub task_id: String,
    pub attempt: u32,
    pub outcome: TaskOutcome,
    pub exit_code: i32,
    pub duration_ms: u64,
    pub xcom_json: String,
    pub error: String,
    pub metrics: HashMap<String, f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum TaskOutcome {
    Unspecified = 0,
    Success = 1,
    Failed = 2,
    Retry = 3,
    Skipped = 4,
}

// ─── Heartbeat & Directives ───────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkerHeartbeat {
    pub worker_id: String,
    pub active_tasks: u32,
    pub cpu_percent: f64,
    pub memory_percent: f64,
    pub disk_percent: f64,
    pub running_assignments: Vec<String>,
    pub timestamp_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CoordinatorDirective {
    CancelTask {
        assignment_id: String,
        reason: String,
    },
    Drain {
        reason: String,
        grace_period_secs: u32,
    },
    HeartbeatAck {
        timestamp_ms: i64,
    },
}

// ─── Log Streaming ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskLogEntry {
    pub assignment_id: String,
    pub worker_id: String,
    pub level: LogLevel,
    pub message: String,
    pub timestamp_ms: i64,
    pub metadata_json: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum LogLevel {
    Unspecified = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
}

// ─── Cluster Status ───────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterStatusResponse {
    pub health: ClusterHealth,
    pub workers: Vec<WorkerStatus>,
    pub active_runs: u32,
    pub running_tasks: u32,
    pub queued_tasks: u32,
    pub uptime_secs: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum ClusterHealth {
    Unspecified = 0,
    Healthy = 1,
    Degraded = 2,
    Unhealthy = 3,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkerStatus {
    pub worker_id: String,
    pub hostname: String,
    pub state: WorkerState,
    pub capacity: u32,
    pub active_tasks: u32,
    pub pool_affinity: Vec<String>,
    pub last_heartbeat_ms: i64,
    pub cpu_percent: f64,
    pub memory_percent: f64,
    pub labels: HashMap<String, String>,
    pub registered_at_ms: i64,
    pub tasks_completed: u64,
    pub tasks_failed: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum WorkerState {
    Unspecified = 0,
    Active = 1,
    Draining = 2,
    Disconnected = 3,
    Dead = 4,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ack {
    pub success: bool,
    pub message: String,
}

impl Ack {
    pub fn ok() -> Self {
        Self {
            success: true,
            message: String::new(),
        }
    }

    pub fn error(msg: impl Into<String>) -> Self {
        Self {
            success: false,
            message: msg.into(),
        }
    }
}
